version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'

  url_shortener:
    build: .
    restart: always
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/url_shortener
    ports:
      - "4000:4000"
    environment:
      # Database
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'password'
      DB_HOST: db
      DB_PORT: '5432'
      # Rails
      RAILS_ENV: "development"
    depends_on:
      - db
    links:
      - db